### ISSUE TITLE
CPU alignment issue while loading video using decord

### ISSUE THREAD

**Issue by tea1528** [open-mmlab/mmaction#12]
Hi, I was using decord to load videos from Kinetics400 but the below error occurred.

```
[08:31:57] /home/shwancha/mmaction/third_party/decord/src/video/video_reader.cc:145: Video Reader width: 454 is not aligned with CPU alignment preference, causing non-compact array with degraded performance. Automatically round up resolution to: 464 x 261
terminate called after throwing an instance of 'dmlc::Error'
  what():  [08:31:57] /home/shwancha/mmaction/third_party/decord/src/video/ffmpeg/ffmpeg_common.h:192: Check failed: p->linesize[0] % p->width == 0 AVFrame data is not a compact array. linesize: 1440 width: 464

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(dmlc::StackTrace[abi:cxx11](unsigned long)+0x9d) [0x7f2eab46aefa]
[bt] (1) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2f) [0x7f2eab46b223]
[bt] (2) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(decord::ffmpeg::ToDLTensor(std::shared_ptr<AVFrame>, DLTensor&, long*)+0x253) [0x7f2eab4d1c8f]
[bt] (3) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(decord::ffmpeg::AsNDArray(std::shared_ptr<AVFrame>)+0xc5) [0x7f2eab4d200f]
[bt] (4) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(decord::ffmpeg::FFMPEGThreadedDecoder::ProcessFrame(std::shared_ptr<AVFrame>, decord::runtime::NDArray)+0x2bf) [0x7f2eab4d100f]
[bt] (5) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(decord::ffmpeg::FFMPEGThreadedDecoder::WorkerThread()+0x50d) [0x7f2eab4d172f]
[bt] (6) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(void std::_Mem_fn_base<void (decord::ffmpeg::FFMPEGThreadedDecoder::*)(), true>::operator()<, void>(decord::ffmpeg::FFMPEGThreadedDecoder*) const+0x65) [0x7f2eab4db283]
[bt] (7) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(void std::_Bind_simple<std::_Mem_fn<void (decord::ffmpeg::FFMPEGThreadedDecoder::*)()> (decord::ffmpeg::FFMPEGThreadedDecoder*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>)+0x43) [0x7f2eab4db217]
[bt] (8) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(std::_Bind_simple<std::_Mem_fn<void (decord::ffmpeg::FFMPEGThreadedDecoder::*)()> (decord::ffmpeg::FFMPEGThreadedDecoder*)>::operator()()+0x2c) [0x7f2eab4db110]
[bt] (9) /usr/local/lib/python3.6/site-packages/decord-0.0.1-py3.6.egg/decord/libdecord.so(std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (decord::ffmpeg::FFMPEGThreadedDecoder::*)()> (decord::ffmpeg::FFMPEGThreadedDecoder*)> >::_M_run()+0x1c) [0x7f2eab4db02a]


Aborted (core dumped)
```

Does this mean that I have fix the resolution that is aligned with CPU alignment preference?

**Comment by zhaoyue-zephyrus** [comment]
Hi @tea1528 ,

Yes, I would recommend resizing all videos into a fixed resolution (340x256). Using Decord will face this problem currently (I will try reaching the author for discussion).

I found that I didn't include the script for resizing in the data preparation part. But I think it should be okay with you, right?

Check if the resizing will work and let me know.

**Comment by tea1528** [comment]
Thanks for a swift reply.

My only concern is that resizing to a fixed resolution might lead to bad performance for dataset like Kinetics which have various resolutions and aspect ratio (there are videos in landscape and portrait shape). As a result, I only resized either width or height to 256 to maintain the aspect ratio of the frame.

1. Have you experienced any performance drop by resizing?
2. Is there a reason you chose decord over OpenCV, [Lintel](https://github.com/dukebw/lintel), or [DALI](https://github.com/NVIDIA/DALI)?

**Comment by zhaoyue-zephyrus** [comment]
Hi @tea1528 ,

I understand your concerns. My response is as follows,

> Have you experienced any performance drop by resizing?

What you mention is similar to the training style provided in [Non-local Res3D](https://arxiv.org/abs/1711.07971). On contrary, we use fixed aspect ratio because in the phase of data augmentation, we also use scale jittering. Therefore, the effect of various original aspect ratios will be erased. Actually I haven't explored the difference between these styles very rigorously (since this version is quite an early release). But according to the reported value (73.3% in NL's paper and 72.9% in ours), I consider the difference should not be big.

I can run a fair comparison when computational resources are available, and will put it here.

> Is there a reason you chose decord over OpenCV, Lintel, or DALI?

Actually we do have support for decoding using OpenCV. By setting `use_decord=False` as default in [config](https://github.com/open-mmlab/mmaction/blob/master/configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2_video.py#L42), it loads videos using [mmcv](https://github.com/open-mmlab/mmcv) which is in essence a wrapper for OpenCV. In our experiment, this will be around 2x slower than using decord. Seems that decord has some optimization for random frame accessing, which is very good for TSN.

I didn't know Lintel before, but it appears doing similar thing like decord. DALI would be a nice try to add in later release since its support of CUDA decoding.

**Comment by zhreshold** [comment]
Decord actually support CUDA/NVDEC for video decoding and the interface is identical to CPU.
