### ISSUE TITLE
The Kinectis link is broken

### ISSUE THREAD

**Issue by ciwei123** [open-mmlab/mmaction#144]
@zhaoyue-zephyrus Hi! Thanks for your sharing. And I found that the link to download Kinetics dataset is broken. For example, https://deepmind.com/documents/65/kinetics_val.zip. Could you update the link? In addition， Kinetic official website has 222,580 training videos，18291 validation videos, but you said that you are using 240436 training videos,19796 testing videos.Could you tell me the difference between the official data with your data? Thank you very much!!

**Comment by kennymckormick** [comment]
The official list of Kinetics-400 can be obtained here: https://storage.googleapis.com/deepmind-media/Datasets/kinetics400.tar.gz. We will update the links in our repo. Our videos were downloaded when Kinetics-400 released for the first time. As time goes on, some Youtube videos become invalid. Maybe that's why the official Kinetics-400 dataset shrinks.

**Comment by jaypatravali** [comment]
@kennymckormick any update for the kinetics link or workaround to this?
