### ISSUE TITLE
How to solve it？KeyError: 'frame_dir'....Thanks!

### ISSUE THREAD

**Issue by BinglinShu** [open-mmlab/mmaction#188]
when run:
python demo/demo.py configs/recognition/i3d/i3d_r50_fast_32x2x1_100e_kinetics400_rgb.py checkpoint/i3d/i3d_r50_fast_32x2x1_100e_kinetics400_rgb_20200612-000e4d2a.pth demo/demo.mp4 demo/label_map.txt

An error occurred when running the demo according to the instructions！

Traceback (most recent call last):
  File "demo/demo.py", line 35, in <module>
    main()
  File "demo/demo.py", line 27, in main
    results = inference_recognizer(model, args.video, args.label)
  File "/root/mmaction/mmaction/apis/inference.py", line 63, in inference_recognizer
    data = test_pipeline(data)
  File "/root/mmaction/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/root/mmaction/mmaction/datasets/pipelines/loading.py", line 576, in __call__
    directory = results['frame_dir']
KeyError: 'frame_dir'

![image](https://user-images.githubusercontent.com/29726904/87115590-4cf97d00-c2a6-11ea-9613-a215f2912df6.png)

**Comment by JoannaLXY** [comment]
Hi @BinglinShu. Thanks for this issue. 

This is because the config file you use is for `RawframeDataset` but the demo uses video. Different datasets type has different data pipelines and causes your error. To fix this problem, you may want to use a config file for `VideoDataset` or you can manually change the `dataset_type` and `test_pipeline` part in the config file. You can refer to this [video inference config file for TSN](https://github.com/open-mmlab/mmaction/blob/master/configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py). 

For your convenience, we will also add more config files for demo soon.

**Comment by JoannaLXY** [comment]
Update:

We have added some config files for the demo in MMAction2. You can refer to [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/i3d/i3d_r50_video_inference_32x2x1_100e_kinetics400_rgb.py) for the inference config for i3d model.
