### ISSUE TITLE
cannot from mmcv.runner import parallel_test

### ISSUE THREAD

**Issue by fangwudi** [open-mmlab/mmaction#212]
use tools/test_localizer.py and then error:cannot from mmcv.runner import parallel_test

**Comment by zhaoyue-zephyrus** [comment]
Hi, this is due to the mismatch of mmcv version. As a workaround, please downgrade the mmcv version (say `pip install mmcv==0.2.12`) and then run `tools/test_localizer.py`. To match mmcv>1.0, please look at [this commit](https://github.com/open-mmlab/mmaction/commit/b5487abfc67838783accea36e9a86220b4ebccf5) for `tools/test_detector.py`.
