### ISSUE TITLE
CMake 3.8 or higher is required.

### ISSUE THREAD

**Issue by huiyang865** [open-mmlab/mmaction#4]
Hi,

When I build the Decord library to install the video loader, following the steps:

```
cd third_party/decord
mkdir build && build
cmake .. -DUSE_CUDA=0
make
```

An error appears while run this command "cmake .. -DUSE_CUDA=0":
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.8 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!
```

But I update the CMake version, ubuntu system reminder:
cmake is already the newest version (3.5.1-1ubuntu3).

**Comment by zhaoyue-zephyrus** [comment]
Hi @huiyang865 ,

Thanks for reporting this issue.

You are encountering this possibly because you are using some older version of Ubuntu. (You can report it after this comment).

As stated in the error log, you need cmake with version greater than 3.8. You can download it from the [official website](https://cmake.org/download/), build from scratch, and choosing the new cmake manually when install decord.

```shell
wget https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.sh
bash cmake-3.13.5-Linux-x86_64.sh
```
